# Generated by Django 5.2 on 2025-05-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imgae',
            field=models.ImageField(blank=True, upload_to='blog/images/'),
        ),
    ]
