# Generated by Django 5.2 on 2025-05-18 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_imgae'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='imgae',
            new_name='image',
        ),
    ]
